version: '3'

services:
  django_backend:
    container_name: django-backend
    build:
      context: .
      dockerfile: DockerFile
    entrypoint: /entrypoint.sh
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    volumes:
      - .:/django_project
    depends_on:
      web_app_db:
        condition: service_healthy
    restart: on-failure
